version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: swifttrack-postgres-dev
    environment:
      POSTGRES_DB: swifttrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    container_name: swifttrack-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: swifttrack-rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_dev_data:/var/lib/rabbitmq
      - ./infra/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./infra/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    container_name: swifttrack-minio-dev
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_dev_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Mock External Services
  mock-cms:
    image: mockserver/mockserver:latest
    container_name: swifttrack-mock-cms-dev
    ports:
      - "8080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/cms-expectations.json
    volumes:
      - ./infra/mocks/cms-expectations.json:/config/cms-expectations.json

  mock-ros:
    image: mockserver/mockserver:latest
    container_name: swifttrack-mock-ros-dev
    ports:
      - "8081:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/ros-expectations.json
    volumes:
      - ./infra/mocks/ros-expectations.json:/config/ros-expectations.json

  # WMS TCP Mock Server
  mock-wms:
    build:
      context: ./infrastructure/mocks/wms-service
      dockerfile: Dockerfile
    container_name: swifttrack-mock-wms-dev
    ports:
      - "8082:8082"

volumes:
  postgres_dev_data:
  redis_dev_data:
  rabbitmq_dev_data:
  minio_dev_data:

networks:
  default:
    name: swifttrack-dev-network
